// Platform/Fate generic events that the vampire reducer also handles
const SHARED_EVENT_TYPES = [
  "CHARACTER_CREATED",
  "CHARACTER_DELETED",
  "CHARACTER_UPDATED",
  "CHARACTER_MOVED",
  "CHARACTER_NAME_UPDATED",
  "CHARACTER_BIO_UPDATED",
  "CHARACTER_IMAGE_UPDATED",
  "CHARACTER_SHEET_ASPECT_UPDATED",
  "CHARACTER_SKILL_UPDATED",
  "CHARACTER_REFRESH_UPDATED",
  "CHARACTER_CONSEQUENCE_UPDATED",
  "CHARACTER_CONSEQUENCE_DELETED",
  "CHARACTER_CONSEQUENCE_SLOT_ADDED",
  "CHARACTER_NOTE_ADDED",
  "CHARACTER_NOTE_DELETED",
  "FP_GAINED",
  "FP_SPENT",
  // Stress events — vampire reducer extends these to accept track: "BLOOD"
  "STRESS_MARKED",
  "STRESS_CLEARED",
  "STRESS_TRACK_EXPANDED",
  "STRESS_TRACK_REDUCED",
  "STRESS_BOX_VALUE_UPDATED",
  // Inventory / Stunt
  "CHARACTER_STUNT_UPDATED",
  "CHARACTER_STUNT_DELETED",
  "CHARACTER_INVENTORY_UPDATED",
  "SKILL_RESOURCE_INIT",
  "SKILL_RESOURCE_UPDATED",
  // Arena
  "ZONE_CREATED",
  "ASPECT_CREATED",
] as const;

// Vampire-exclusive event types
const VAMPIRE_EXCLUSIVE_EVENT_TYPES = [
  "VAMPIRE_GENERATION_UPDATED",
  "VAMPIRE_DISCIPLINE_UPDATED",
  "VAMPIRE_DISCIPLINE_DELETED",
  "VAMPIRE_HUNGER_CONSEQUENCE_UPDATED",
  "VAMPIRE_HUNGER_CONSEQUENCE_DELETED",
  "VAMPIRE_HUNGER_CONSEQUENCE_SLOT_ADDED",
] as const;

export const VAMPIRE_EVENT_TYPES = [
  ...SHARED_EVENT_TYPES,
  ...VAMPIRE_EXCLUSIVE_EVENT_TYPES,
] as const;
